const { Schema , model} = require('');
new PersonaSchema = new Schema({
    CodPersona : string,
	IdTipoDocumento : int,
	NumDocIdentidad : String,
	Nombre: string,
	ApellidoPaterno : string,
	ApellidoMaterno : string,
	Sexo : string,
	FechaNacimiento:Date,
	IdPertenenciaEtnica: int,
	IdPaisNacimiento: int, 
	CodUbigeoNacimiento: string,
	Foto: string,
	IdGradoInstruccion: int,
	IdReligion:int,
	CentroEducativo: string,
	IdEstadoCivil: int,
	IdOcupacion: int,
	TelefonoFijo: string,
	TelefonoMovil: string,
	Correo: string,
	IdTipoPersona : int,
	TratamientoDato : Boolean,
	TerminoCondicion : Boolean,
	CodUsuario: string,
	CodUsuCreaRegistro : string,
	FechaCreaRegistro: datetime,
	CodUsuModificaRegistro : String,
	FechaModificaRegistro : datetime,
	EstadoRegistro : Boolean,
}
)
